---
title: "Analysis on Health and Economic Effects of Severe Weather Events"
author: "Daniel DeWaters"
date: "10/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load dependencies
#install.packages("R.utils") ###########
library(R.utils)
library(dplyr)
```


## Data Processing

I start by downloading the data file, unzipping it, and reading it in using read.csv().

```{r getData}
data_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
data_file_name <- "./data/repdata_data_StormData.csv.bz2"
unzipped_file_name <- "./data/repdata_data_StormData.csv"

if(!file.exists(unzipped_file_name)){
  download.file(data_url, destfile=data_file_name, method="curl")
  bunzip2(data_file_name, destname=unzipped_file_name, remove=FALSE, overwrite=TRUE)
}

raw_data <- read.csv(unzipped_file_name)
```


```{r cleandata}
clean_data <- 
  raw_data %>%
  mutate(EVTYPE = tolower(EVTYPE)) %>%
  # Un-abbreviate Thunderstorm
  mutate(EVTYPE = gsub("tstm", "thunderstorm", EVTYPE)) %>%
  # Remove plurals
  mutate(EVTYPE = gsub("winds", "wind", EVTYPE)) %>%
  mutate(EVTYPE = gsub(".*flood.+"))
  mutate(EVTYPE = gsub(" \\d+$", "", EVTYPE))
  

ev_type_counts <- sort(table(clean_data$EVTYPE), decreasing=TRUE)
ev_type_counts[1:10]


```

```{r testing}
ev_df <- as.data.frame(ev_type_counts)
floods <- grep("flood", ev_df$Var1)
ev_df[floods,]
```
## Results
